[package]
name = "ical-rs"
description = "iCalendar parser, validator, editor and builder library for Rust"
version = "0.1.0"
authors = ["Clément DOUIN (soywod) <pimalaya.org@posteo.net>"]
rust-version = "1.88"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["data-structures", "parser-implementations", "encoding", "no-std"]
keywords = ["icalendar", "calendar", "caldav", "rfc5545", "codec"]
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/ical-rs/latest/ical"
repository = "https://github.com/pimalaya/ical-rs"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "ical"

[features]
default = ["parser", "quoted-printable", "base64", "encoding"]
parser = ["dep:memchr"]
jcal = ["parser", "dep:serde_json"]
jscalendar = ["jcal"]
quoted-printable = ["dep:quoted_printable"]
base64 = ["dep:base64"]
encoding = ["dep:encoding_rs"]

[[bench]]
name = "parse"
path = "benches/parse.rs"
harness = false
required-features = ["parser"]

[[example]]
name = "parse_edit_export"
path = "examples/parse_edit_export.rs"
required-features = ["parser"]

[[example]]
name = "strict_builder"
path = "examples/strict_builder.rs"
required-features = ["parser"]

[[example]]
name = "raw_builder"
path = "examples/raw_builder.rs"
required-features = ["parser"]

[dev-dependencies]
calcard = { version = "0.3", default-features = false }
criterion = { version = "0.8", default-features = false, features = ["cargo_bench_support"] }
ical_crate = { package = "ical", version = "0.11", default-features = false, features = ["ical"] }
icalendar = { version = "0.17", default-features = false, features = ["parser"] }

[dependencies]
base64 = { version = "0.23", default-features = false, features = ["alloc"], optional = true }
encoding_rs = { version = "0.8", default-features = false, features = ["alloc"], optional = true }
memchr = { version = "2", default-features = false, optional = true }
quoted_printable = { version = "0.5", default-features = false, optional = true }
serde_json = { version = "1", default-features = false, features = ["alloc"], optional = true }
